language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.3.1
    - DJANGO_VERSION=1.4.2
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - bash test.sh
